### ISSUE TITLE
User can view movie list #1

### ISSUE THREAD

**Issue by Zoey1318** [Zoey1318/ajax-project#1]
## 📐 Functionality

> ##### When the user login for the first time, list of movie genre will appear for user to select or skip. User can view preferred genre on top of the home page along with other movie list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Web_Main](https://user-images.githubusercontent.com/111097580/210035246-dbb70dab-9f18-4f25-ae33-65334d424fe3.png)
![Web_Genre select](https://user-images.githubusercontent.com/111097580/210035256-3314b59b-b280-43fd-9e48-27e491ff0dec.png)
![Web_Home](https://user-images.githubusercontent.com/111097580/210035262-51154f84-5f80-4f40-bd11-1460fca940bc.png)
![Mobile_Main](https://user-images.githubusercontent.com/111097580/210035300-0b96a4a9-be12-4431-85b9-daf111141c78.png)
![Mobile_Genre select](https://user-images.githubusercontent.com/111097580/210035305-eb6327ce-77e1-472d-8aa4-79d39b9be25a.png)
![Mobile_Home](https://user-images.githubusercontent.com/111097580/210035310-fc5e1db7-96dc-4e90-b603-52401bda0a78.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create main page to the HTML.
- [ ] Create genre select page to the HTML.
- [ ] Create home page to the HTML.
- [ ] Add styles for main page in CSS.
- [ ] Add styles for genre select page in CSS.
- [ ] Add styles for home page in CSS.
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Listen for 'Start Now' button to access genre select page.
  - [ ] Listen for 'Skip' event to access home page.
  - [ ] Listen for 'Previous' event to go back to main page.
  - [ ] Listen for 'Genre' box to change color of box
  - [ ] Listen for 'Check' event to store selected genre, which the genre tab will appear on top of the home page and access to home page.
  - [ ] Verify that selected genre are saved to local storage
- [ ] Listen for 'I already have a profile' button to access home page.
- [ ] Remove all CSS properties that have no effect.
- [ ] Remove all console logs.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
